openapi: "3.0.1"
info:
  title: "Walt Disney World API"
  description: An api that encompasses the Walt Disney World Resort parks, rides, resorts, and restaurants. This API follows the OpenAPI standard.
  version: "0.1.0"
  contact:
    name: Developer Support
    url: disapi.co/support
    email: support@disapi.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: https://disapi.co/api
  description: Production Server
- url: http://localhost/api
  description: Local Server

tags:
  - name: parks
    description: Endpoints for getting and working with the parks
  - name: resorts
    description: Endpoints for getting and working with the resorts
  - name: restaurants
    description: Endpoints for getting and working with the restaurants
  - name: rides
    description: Endpoints for getting and working with the rides
paths:
  /resorts:
    get:
      summary: List resorts at Walt Disney World
      description: Get a list of resorts at Walt Disney World
      operationId: getResorts
      tags:
        - resorts
      responses:
        200:
          $ref: '#/components/responses/ResortsResponse'
        400:
          description: The request you made could not be fulfilled right now.
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
    post:
      summary: Create a new resort resource
      operationId: createResort
      description: Create a new resort resource for the Walt Disney World Resort
      tags:
        - resorts
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ResortForm'
      responses:
        201:
          description: Created'
          headers:
            location:
              $ref: '#/components/headers/Location'
        400:
          description: The request you made could not be fulfilled right now.
        404:
          description: Resource could not be found
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
  /resorts/{id}:
    get:
      summary: List a specific resort resource by ID
      description: Get a specific resort resource by ID
      operationId: getResort
      parameters:
      - $ref: '#/components/parameters/resortId'
      tags:
        - resorts
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ResortForm'
      responses:
        200:
          $ref: '#/components/responses/ResortResponse'
        400:
          description: The request you made could not be fulfilled right now.
        404:
          description: Resource could not be found
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
    put:
      summary: Edit a specific resort resource by ID
      description: Find and edit a specific resort resource by its ID
      operationId: editResort
      parameters:
      - $ref: '#/components/parameters/resortId'
      tags:
        - resorts
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ResortForm'
      responses:
        200:
          description: Created
          headers:
            location:
              $ref: '#/components/headers/Location'
        400:
          description: The request you made could not be fulfilled right now.
        404:
          description: Resource could not be found
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
    delete:
      summary: Delete resort resource by ID
      operationId: deleteResort
      parameters:
      - $ref: '#/components/parameters/resortId'
      tags:
        - resorts
      responses:
        204:
          description: No Content
        400:
          description: The request you made could not be fulfilled right now.
        404:
          description: Resource Not Found
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
  /rides:
    get:
      summary: List rides at Walt Disney World
      description: |
        Get a list of rides at all Walt Disney World Parks
      operationId: getRides
      tags:
        - rides
      responses:
        200:
          $ref: '#/components/responses/RidesResponse'
        400:
          description: The request you made could not be fulfilled right now.
        404:
          description: The requested resources could not be found
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
    post:
      summary: Create a new ride resource
      description: Create a new ride resource for the Walt Disney World Resort
      operationId: createRides
      tags:
        - rides
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RideForm'
      responses:
        201:
          description: OK
          headers:
            location:
              $ref: '#/components/headers/Location'
        400:
          description: The request you made could not be fulfilled right now.
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
  /rides/{id}:
    get:
      summary: Get ride by ID
      description: Get a ride at Walt Disney World by ID
      operationId: getRide
      parameters:
        - $ref: '#/components/parameters/rideId'
      tags:
        - rides
      responses:
        200:
          $ref: '#/components/responses/RideResponse'
        400:
          description: The request you made could not be fulfilled right now.
        404:
          description: Resource Not Found
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
    put:
       summary: Edit a ride by ID
       description: Edit a ride in the resource collection by ID
       operationId: editRide
       parameters:
         - $ref: '#/components/parameters/rideId'
       tags:
         - rides
       requestBody:
         content:
           application/x-www-form-urlencoded:
             schema:
               $ref: '#/components/schemas/RideForm'
       responses:
         201:
           description: Created
           headers:
             location:
               $ref: '#/components/headers/Location'
         400:
           description: The request you made could not be fulfilled right now.
         418:
           description: I am a teapot.
         451:
           description: Censored for legal reasons.
    delete:
      summary: Delete ride resource by ID
      operationId: deleteRide
      parameters:
        - $ref: '#/components/parameters/rideId'
      tags:
        - rides
      responses:
        204:
          description: No Content
        400:
          description: The request you made could not be fulfilled right now.
        404:
          description: Resource Not Found
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
  /restaurants:
    get:
      summary: List restaurants at Walt Disney World
      description: Get a list of restaurants at all parks
      operationId: getRestaurants
      tags:
        - restaurants
      responses:
        200:
          $ref: '#/components/responses/RestaurantsResponse'
        400:
          description: The request you made could not be fulfilled right now.
    post:
      summary: Create a new restaurant resource
      description: Create a new restaurnat resource at Walt Disney World
      operationId: createRestaurant
      tags:
        - restaurants
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RestaurantForm'
      responses:
        201:
          description: Created
          headers:
            location:
              $ref: '#/components/headers/Location'
        400:
          description: The request you made could not be fulfilled right now.
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
  /restaurants/{id}:
    get:
      summary:  List a single restaurant resource from the collection by ID
      description: Get a single restaurant resource by ID
      operationId: getRestaurant
      parameters:
        - $ref: '#/components/parameters/restaurantId'
      tags:
        - restaurants
      responses:
        200:
          $ref: '#/components/responses/RestaurantResponse'
        400:
          description: The request you made could not be fulfilled right now
        404:
          description: Resource Not Found
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
    put:
      summary: Edit a single restaurant resource in the collection by ID
      description: Edit a restaurant by ID
      operationId: editRestaurant
      parameters:
        - $ref: '#/components/parameters/restaurantId'
      tags:
        - restaurants
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RestaurantForm'
      responses:
        201:
          description: Created
          headers:
            location:
              $ref: '#/components/headers/Location'
        400:
          description: The request you made could not be fulfilled right now.
        404:
          description: The resource could not be found.
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
    delete:
      summary: Remove a resource from the restaurants collection
      description: Remove a resource from the restaurants collection by ID
      operationId: deleteRestaurant
      tags:
        - restaurants
      responses:
        204:
          description: No Content
        400:
          description: The request you made could not be fulfilled right now.
        404:
          description: The resource could not be found.
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
  /parks:
    get:
      summary: List all parks at Walt Disney World
      description: Get a list of all parks at Walt Disney World
      operationId: getParks
      tags:
        - parks
      responses:
        200:
          $ref: '#/components/responses/ParksResponse'
        400:
          description: The request you made could not be fulfilled right now.
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
    post:
      summary: Create a new park resource in the collection
      description: Create a new park at Walt Disney World
      operationId: createPark
      tags:
        - parks
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ParkForm'
      responses:
        201:
          description: Created
          headers:
            location:
              $ref: '#/components/headers/Location'
        400:
          description: The request you made could not be fulfilled right now.
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
  /parks/{id}:
    get:
      summary: List a park by ID
      description: Get a park at Walt Disney World by ID
      operationId: getPark
      parameters:
        - $ref: '#/components/parameters/parkId'
      tags:
        - parks
      responses:
        200:
          $ref: '#/components/responses/ParkResponse'
        400:
          description: The request you made could not be fulfilled right now.
        404:
          description: Resource Not Found
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
    put:
      summary: Edit a resource by ID
      description: Edit a park resource by an ID
      operationId: editPark
      parameters:
        - $ref: '#/components/parameters/parkId'
      tags:
        - parks
      responses:
        200:
          description: OK
          headers:
            location:
              $ref: '#/components/headers/Location'
        400:
          description: The request you made could not be fulfilled right now.
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
    delete:
      summary: Remove a resource from the collection
      description: Remove a resource from the collection by ID
      operationId: deletePark
      parameters:
        - $ref: '#/components/parameters/parkId'
      tags:
        - parks
      responses:
        204:
          description: No Content
        400:
          description: The request you made could not be fulfilled right now.
        404:
          description: Resource Not Found
        418:
          description: I am a teapot.
        451:
          description: Censored for legal reasons.
components:
  schemas:
    Rides:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    Ride:
      type: object
      properties:
        name:
          type: string
        parkId:
          type: integer
        openingYear:
          type: integer
        rideType:
          type: string
        rideVehicle:
          type: string
        interactiveQueue:
          type: boolean
        giftStoreFinish:
          type: boolean
        singleRider:
          type: integer
        ridePhoto:
          type: integer
        heightRestriction:
          type: integer
    RideForm:
      type: object
      required:
        - name
          parkId
          openingYear
          rideType
          rideVehicle
          interactiveQueue
          giftShopFinish
          singleRider
          ridePhoto
          heightRestriction
      properties:
        name:
          type: string
        parkId:
          type: integer
        openingYear:
          type: integer
        rideType:
          type: string
        rideVehicle:
          type: string
        interactiveQueue:
          type: boolean
        giftStoreFinish:
          type: boolean
        singleRider:
          type: integer
        ridePhoto:
          type: integer
        heightRestriction:
          type: integer
    Resorts:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    Resort:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        parkId:
          type: integer
        transportOptions:
          type: array
          items:
            type: string
        category:
          type: string
        numOfRooms:
          type: integer
        quickServiceRestaurants:
          type: boolean
        tableServiceRestaurants:
          type: boolean
        giftShop:
          type: boolean
        arcade:
          type: boolean
        pool:
          type: boolean
    ResortForm:
      type: object
      required:
        - name
          parkId
          resortType
          transportOptions
          category
          numOfRooms
          quickServiceRestaurants
          tableServiceRestaurants
          giftShop
          arcade
          pool
      properties:
        name:
          type: string
        parkId:
          type: integer
        openingYear:
          type: integer
        resortType:
          type: string
        transportOptions:
          type: string
        category:
          type: string
        numOfRooms:
          type: integer
        quickServiceRestaurants:
          type: boolean
        tableServiceRestaurants:
          type: boolean
        giftShop:
          type: boolean
        arcade:
          type: boolean
        pool:
          type: boolean
    Parks:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    Park:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        centralAttraction:
          type: string
        yearOpened:
          type: string
        rideCount:
          type: integer
        restaurantCount:
          type: integer
        size:
          type: integer
        resortCount:
          type: integer
        fireworks:
          type: boolean
    ParkForm:
      type: object
      required:
        - name
          centralAttraction
          yearOpened
          rideCount
          restaurantCount
          resortCount
          size
          fireworks
      properties:
        name:
          type: string
        centralAttraction:
          type: string
        yearOpened:
          type: integer
        rideCount:
          type: integer
        restaurantCount:
          type: integer
        resortCount:
          type: integer
        size:
          type: integer
        fireworks:
          type: boolean
    Restaurants:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    Restaurant:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        quickService:
          type: boolean
        tableService:
          type: boolean
        alcohol:
          type: boolean
        diningPlan:
          type: boolean
        mealTypes:
          type: array
          items:
            type: string
        foodTypes:
          type: array
          items:
            type: string
    RestaurantForm:
      type: object
      required:
        - name
          parkId
          quickService
          tableService
          alcohol
          diningPlan
          mealTypes
          foodTypes
      properties:
        name:
          type: string
        parkId:
          type: integer
        quickService:
          type: boolean
        tableService:
          type: boolean
        alcohol:
          type: boolean
        diningPlan:
          type: boolean
        mealTypes:
          type: array
          items:
            type: string
        foodTypes:
          type: array
          items:
            type: string
  parameters:
    restaurantId:
      name: id
      in: path
      required: true
      schema:
        type: integer
      description: The ID of the restaurant
    resortId:
      name: id
      in: path
      required: true
      schema:
        type: integer
      description: The ID of the resort
    rideId:
      name: id
      in: path
      required: true
      schema:
        type: integer
      description: The ID of the ride
    parkId:
      name: id
      in: path
      required: true
      schema:
        type: integer
      description: The ID of the park
  headers:
    Location:
      description: The location of the newly created resource
      schema:
        type: string
  responses:
    RidesResponse:
      description: A list a rides
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Rides'
                minLength: 1
          examples:
            ridesArray:
              $ref: '#/components/examples/RidesResponse'
    RideResponse:
      description: A singluar ride resource by ID
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Ride'
                minLength: 1
          examples:
            ridesArray:
              $ref: '#/components/examples/RideResponse'
    ResortsResponse:
      description: A list a resorts at Walt Disney World
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Resorts'
          examples:
            resortsArray:
              $ref: '#/components/examples/ResortsResponse'
    ResortResponse:
      description: A singular resort resource by ID
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Resort'
          examples:
            resortArray:
              $ref: '#/components/examples/ResortResponse'
    RestaurantsResponse:
      description: A list a restaurant resources
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurants'
                minLength: 1
          examples:
            restaurantsArray:
              $ref: '#/components/examples/RestaurantsResponse'
    RestaurantResponse:
      description: A singular restaurant resource
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurant'
                minLength: 1
          examples:
            restaurantArray:
              $ref: '#/components/examples/RestaurantResponse'
    ParksResponse:
      description: A list a parks at Walt Disney World
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Parks'
                minLength: 1
          examples:
            parksArray:
              $ref: '#/components/examples/ParksResponse'
    ParkResponse:
      description: A park at Walt Disney World by ID
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Park'
                minLength: 1
          examples:
            parkArray:
              $ref: '#/components/examples/ParkResponse'
  examples:
    ResortsResponse:
      summary: An example response of resorts resource at Walt Disney World
      value:
        data:
          - id: 1
            name: All-Star Movies Resort
            parkId: 4
          - id: 2
            name: All-Star Music Resort
            parkId: 4
          - id: 3
            name: All-Star Sports Resort
            parkId: 4
    ResortResponse:
      summary: An example response of a resort resource at Walt Disney World
      value:
        data:
          - id: 1
            name: All-Star Movies Resort
            parkId: 4
            resortType: Value,
            transportationOptions: [
                Bus
            ]
            category: Music,
            numOfRooms: 1604,
            quickServiceRestaurants: true,
            tableServiceRestaurants: false,
            giftShop: true,
            arcade: true,
            pool: true
    RidesResponse:
      summary: An example response of rides resources at Walt Disney World
      value:
        data:
          - id: 1
            name: Walt Disney World Railroad
          - id: 2
            name: Jungle Cruise
          - id: 3
            name: The Magic Carpets of Aladdin
    RideResponse:
      summary: An example response of a ride
      value:
        data:
          - id: 1
            name: Walt Disney World Railroad
            yearOpened: 1971
            rideType: Transport
            rideVehicle: Train
            interactiveQueue: false
            ridePhoto: false
            singleRider: false
            heightRestriction: false
          - id: 2
            name: Aladdin's Magic Carpets
            yearOpened: 1971
            rideType: Transport
            rideVehicle: Train
            interactiveQueue: false
            ridePhoto: false
            singleRider: false
            heightRestriction: false
          - id: 3
            name: Jungle Cruise
            yearOpened: 1971
            rideType: Transport
            rideVehicle: Train
            interactiveQueue: false
            ridePhoto: false
            singleRider: false
            heightRestriction: false
    RestaurantsResponse:
      summary: An example response of restaurants at Walt Disney World
      value:
        data:
          - id: 1
            name: Aloha Isle
          - id: 2
            name: Auntie Gravity's Galactic Goodies
          - id: 3
            name: Be Our Guest Restaurant
    RestaurantResponse:
      summary: An example response of a restaurant
      value:
        data:
          - id: 1
            name: Aloha Isle,
            quickService: true,
            tableService: false,
            alcohol: false,
            diningPlan: true,
            mealTypes: [
                Snacks,
            ]
            foodTypes: [
                Snacks,
                Dole Whip
            ]
    ParksResponse:
      summary: An exmaple response of parks at Walt Disney World
      value:
        data:
          - id: 1
            name: Magic Kingdom
          - id: 2
            name: Epcot
          - id: 3
            name: Hollywood Studios
          - id: 4
            name: Animal Kingdom
    ParkResponse:
      summary: An exmaple response of a park at Walt Disney World
      value:
        data:
          - id: 1
            name: Magic Kingdom
            centralAttraction: Cinderella's Castle
            yearOpened: 1971
            rideCount: 42
            restaurantCount: 31
            size: 107
            resortCount: 6
            fireworks: 1
  links:
    ParkRides:
      operationId: getParkRides
      parameters:
        id: $response.body#/data/0/id
      description: |
        Using the id of the park can, you can get its rides
        by ising it as the `id` parameter in `GET /parks/{id}/rides`
    ParkRestaurants:
      operationId: getParkRestaurants
      parameters:
        id: $response.body#/data/0/id
      description: |
        Using the id of the park can, you can get its restaurants
        by using it as the `id` parameter in `GET /parks/{id}/restaurants`
